### ISSUE TITLE
Exercise 1.9: inclusive or exclusive range

### ISSUE THREAD

**Issue by Funatiq** [dabeaz-course/practical-python#17]
From the description it is not clear if the extra payment start and/or end month should be included in the range. The exercise asks for "4 years starting in year 5", the code shows an exclusive range [60, 108], but the solution uses an inclusive range with ">=" and  "<=" which results in 49 months.

**Comment by dabeaz** [comment]
Many fundamental parts of Python including slices and ranges require one to think about the difference between inclusive and exclusive ranges.    The ambiguity in the description might be intentional ;-).

**Comment by Funatiq** [comment]
While I do agree that thinking about ranges is important, the solution resulting in 49 months for a exercise that asks for a duration of 4 years does not seem intended or helpful to me.

**Comment by dabeaz** [comment]
You may be right.   Sometimes things for the in-person setting might not translate to self-study.  I will make a fix.

**Comment by drblanc** [comment]
It seems like the problem is the constants rather than the inequalities.  If someone made extra payments for the first year, starting in month 1 and ending in month 12 would make the most sense.  Without the constants given I would have used start_month=49 and end_month=49+48-1 to start with the first payment of the fifth year and continue for 48 months.

**Comment by dabeaz** [comment]
Oh, that's a good observation.    Will look at it again.
